server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          drishti:
            provider: drishti-auth
            client-id: drishti
            client-secret: pass
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,profile
            redirect-uri: http://localhost:8081/login
        provider:
          drishti-auth:
            issuer-uri: http://localhost:9091

logging:
  level:
    root: INFO