spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: INFO
    org:
      hibernate:
        type: TRACE
      springframework:
        security: INFO
  pattern:
    level:
      org.hibernate.orm.jdbc.bind: TRACE


