server:
  port: 9091

spring:
  application:
    name: auth-service
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      connection:
        CharSet: utf-8
        characterEncoding: utf-8
        useUnicode: true